---
master: true
hostname: ***REMOVED***
ip: ***REMOVED***

dnsservers:
  - ***REMOVED***
  - ***REMOVED***
  - ***REMOVED***
  - ***REMOVED***
  - ***REMOVED***
  - ***REMOVED***

dnskey: ***REMOVED***
dnsttl: 30